### ISSUE TITLE
Use where for udevd/udevadm.

### ISSUE THREAD

**Issue by onodera-punpun** [hut/minirc#24]
My distro (CRUX) stores udevd and udevadm in /sbin, but the script only looks in /usr/bin, I think I simple where solves this.

**Comment by hut** [comment]
Or we can just remove the /usr/bin prefix. I don't think there are any downsides to that

**Comment by onodera-punpun** [comment]
true, I found two more specific CRUX problems, rc uses /usr/sbin/ip but CRUX uses /sbin/ip, and rc looks for the hostname in /etc/hostname but CRUX uses /bin/hostname, I don't know what's more universally uses though.

**Comment by bbenne10** [comment]
@onodera-punpun: `/bin/hostname` and `/etc/hostname` are decidedly not the same thing. One is a file containing nothing but the name of the host and the other is a binary that prints the name of the host. I do see on my Crux machine that /etc/hostname doesn't exist (it's set in `/etc/rc.conf` and `/etc/hosts`, but nowhere else that I can see)

@hut: Maybe rely on the `hostname` binary here? Seems to be the only relatively portable way to determine hostname. (One could also argue that `/etc/hosts` should also be right, but it might not be and the machine could be working just fine)

**Comment by hut** [comment]
The context of the hostname-related code is:
```sh
    echo_color 3 setting hostname...
    cat /etc/hostname >| /proc/sys/kernel/hostname
```

I believe that /bin/hostname will return the same thing that's in /proc/sys/kernel/hostname, so calling /bin/hostname to set /proc/sys/kernel/hostname seems pointless. I haven't tried it though.

Perhaps we just need to specify /etc/hostname as a "configuration file" that is needed by minirc.

**Comment by onodera-punpun** [comment]
Or just add a hostname=something to /etc/minirc instead of a whole new file?

**Comment by bbenne10** [comment]
I hadn't had my coffee yet this morning - so of course you're right. There's got to be a way to know what to set the hostname to. I would say that a variable declaration in /etc/minirc.conf is a good idea then.

**Comment by onodera-punpun** [comment]
@hut you are right, /bin/hostname did not work.

@bbenne10 I added a simple HOSTNAME var to minirc.conf and echo $HOSTNAME |> works like a charm.

**Comment by hut** [comment]
Adding a HOSTNAME variable to minirc.conf seems like the best solution... But in the context that minirc is intended to be a systemd replacement, maybe it's not so bad how it is right now. If you used systemd before, your hostname will already be defined in `/etc/hostname`. So we can share configs between minirc and systemd, and there will be one less thing to worry about during the transition. I'm still undecided.

**Comment by bbenne10** [comment]
so make the default in /etc/minirc something like 
```
HOSTNAME=`cat /etc/hostname`
```
yeah?

**Comment by hut** [comment]
You're a genious. Done, see 59a7f835de644609febc36c334ff340d5b1ba4fa
