### ISSUE TITLE
No working init in RonixOS

### ISSUE THREAD

**Issue by RossComputerGuy** [hut/minirc#29]
So I'm the developer of RonixOS and I'm trying to get this to work with my distro but every time I start minirc, I get the no working init error with error -2, I have a ramdisk setup which is similar to a basic Arch Linux one. The system should just boot but no matter what I do, nothing works.

**Comment by hut** [comment]
Did you install busybox?

Does a /sbin/init exist?

If yes, what's your INIT= kernel parameter that's used during boot?

**Comment by RossComputerGuy** [comment]
Init is not set, busybox is installed, /sbin/init exists

**Comment by RossComputerGuy** [comment]
Got it working, mkinitcpio was broken so I made my own init system. I finally got RonixOS to boot but I'm getting this error
![image](https://user-images.githubusercontent.com/19699320/62269745-d9d65e00-b3e8-11e9-84bd-fb86444d19e0.png)

**Comment by bbenne10** [comment]
Is `/etc/inittab` present? If so, is `/bin/sh` runnable? It seems to be dying frequently in that output, which is suspicious.

**Comment by RossComputerGuy** [comment]
I didn't compile busybox with inittab and it boots fine now but I can't log in. I type in my username and press return and get this.
![image](https://user-images.githubusercontent.com/19699320/62304311-91dc2900-b432-11e9-80c9-c64135faec58.png)

**Comment by bbenne10** [comment]
Honestly, this is a problem with busybox's init and its set up - not with minirc. Not that that means you should close this (that decision belongs to @hut), but this is not *exactly* related to this repo. 

That being said: Do you have busybox `login` compiled and installed? `login` is the tool which `getty` uses to validate logins and obviously if it's not there - you're not getting logged in.

**Comment by RossComputerGuy** [comment]
Everything is working now, it was a missing pam file.

**Comment by bbenne10** [comment]
I'm glad you got it working!
