### ISSUE TITLE
Issue/question about rc

### ISSUE THREAD

**Issue by karabaja4** [hut/minirc#30]
Hey,

I hope there's someone here still :)

So I've been digging a bit through minirc lately, and I stumbled upon something curious.

I'm using the minirc Arch package.

There is a line in inittab that calls the rc script:

```
::shutdown:/sbin/rc shutdown
```

which then causes the following code to execute:

```

on_shutdown() {
    #===================
    # stop the default daemons
    echo_color 3 stopping daemons...
    custom_stop all

    #===================
    # load minirc.local.shutdown
    if [ -x /etc/minirc.local.shutdown ]; then
        echo_color 3 loading /etc/minirc.local.shutdown...
        /etc/minirc.local.shutdown
    fi
```

The thing is, `minirc.local.shutdown` is never actually executed. You can put a line behind `custom_stop all` and it will never execute on shutdown. I debugged this a bit, tracked `custom_stop` to `default_stop all` and this piece of code:

```
default_stop() {
    echo_color 1 stopping "$1"...
    case "$1" in
    all)
        for dmn in $DAEMONS $ENABLED; do
            custom_poll "${dmn##@}" && custom_stop "${dmn##@}"
        done;;
```

So I debugged this further and found out that if I rewrite this code like this:

```
default_stop() {
    echo_color 1 stopping "$1"...
    case "$1" in
    all)
        for dmn in $DAEMONS $ENABLED; do
            custom_poll "${dmn##@}" && custom_stop "${dmn##@}"
        done
        echo "something";;
```

then `on_shutdown` proceedes as expected and executes `minirc.local.shutdown`.

I don't understand, why is this the case? Is bash syntax error somewhere causing this strange behavior?

Regards,

Igor

**Comment by bbenne10** [comment]
Just to be clear: the only difference you've introduced in `default_stop` is the line:

```sh
echo "something"
```
in between the `done` and `;;`, yes?

**Comment by karabaja4** [comment]
That's correct.

**Comment by bbenne10** [comment]
Have you tried a `set -x` in `default_stop` to make sure that the lines you believe are being executed are executed? This will be quite noisy, but might get you a bit further.

I'm not 100% sure I understand the expansion that's occurring here. [This link](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html) has the following to say:

> The word is expanded to produce a pattern and matched according to the rules described below (see Pattern Matching). If the pattern matches the beginning of the expanded value of parameter, then the result of the expansion is the expanded value of parameter with the shortest matching pattern (the ‘#’ case) or the longest matching pattern (the ‘##’ case) deleted. If parameter is ‘@’ or ‘*’, the pattern removal operation is applied to each positional parameter in turn, and the expansion is the resultant list. If parameter is an array variable subscripted with ‘@’ or ‘*’, the pattern removal operation is applied to each member of the array in turn, and the expansion is the resultant list. 

Where `parameter` here is `dmn` and `word` is `@`. This implies to me there may be some issue here, as `$@` seems to be expanded to match `$dmn`, which won't likely work? I'm not terribly familiar with this syntax, so I am likely barking up the wrong tree here, but maybe it's worth echoing what `${dmn##@}` spits out?

This does not, however, explain why things work with the extra `echo` line interleaved...
